# permissions for end users to edit roles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: role-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: irsa-operator
    app.kubernetes.io/part-of: irsa-operator
    app.kubernetes.io/managed-by: kustomize
  name: role-editor-role
rules:
- apiGroups:
  - auth.irsa.aws
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.irsa.aws
  resources:
  - roles/status
  verbs:
  - get
