apiVersion: auth.irsa.aws/v1alpha1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: role-sample
    app.kubernetes.io/part-of: irsa-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: irsa-operator
  name: role-sample
spec:
  # TODO(user): Add fields here
