apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "irsa.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "irsa.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "irsa.fullname" . }}-lease
subjects:
  - kind: ServiceAccount
    name: {{ template "irsa.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
