apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "irsa.fullname" . }}-lease
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "irsa.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  # Read
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "patch", "update", "create"]