name: lint-and-test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  lint-and-test:
    permissions:
      checks: write
      contents: read
    name: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.53
          args: --timeout=5m
          install-mode: "binary"

      - name: install ginkgo
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@v2.11.0
          go install github.com/vektra/mockery/v2@v2.32.0

      - name: check generate mocks and go mod tidy
        run: |
          go mod tidy
          make manifests
          echo "checking for uncommited go mod tidy"
          git diff --exit-code
