name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - uses: actions/checkout@v4

      - uses: ko-build/setup-ko@v0.6
      - run: ko build
